name: Feature Request
description: Suggest a new feature or improvement for Onda
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's your use case?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?
    validations:
      required: false
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of Onda does this relate to?
      options:
        - Terminal
        - Workspaces
        - Tiled Layout
        - Plugins
        - AI Commands
        - Git Integration
        - Settings
        - Keyboard Shortcuts
        - Other
    validations:
      required: true
